#ifndef TEMPLATE
#error "You must define TEMPLATE macro before include this file"
#endif



TEMPLATE(RISCV_BORI4,     "or %0, %1, %2")
TEMPLATE(RISCV_BORU4,     "or %0, %1, %2")
TEMPLATE(RISCV_BORF4,     NULL)
TEMPLATE(RISCV_BORF8,     NULL)

TEMPLATE(RISCV_BXORI4,    "xor %0, %1, %2")
TEMPLATE(RISCV_BXORU4,    "xor %0, %1, %2")
TEMPLATE(RISCV_BXORF4,    NULL)
TEMPLATE(RISCV_BXORF8,    NULL)

TEMPLATE(RISCV_BANDI4,    "and %0, %1, %2")
TEMPLATE(RISCV_BANDU4,    "and %0, %1, %2")
TEMPLATE(RISCV_BANDF4,    NULL)
TEMPLATE(RISCV_BANDF8,    NULL)

TEMPLATE(RISCV_LSHI4,    "shl %0, %1, %2")
TEMPLATE(RISCV_LSHU4,    "shl %0, %1, %2")
TEMPLATE(RISCV_LSHF4,    NULL)
TEMPLATE(RISCV_LSHF8,    NULL)

TEMPLATE(RISCV_RSHI4,    "srl %0, %1, %2")
TEMPLATE(RISCV_RSHU4,    "srl %0, %1, %2")
TEMPLATE(RISCV_RSHF4,    NULL)
TEMPLATE(RISCV_RSHF8,    NULL)

TEMPLATE(RISCV_ADDI4,    "add %0, %1, %2")
TEMPLATE(RISCV_ADDU4,    "add %0, %1, %2")
TEMPLATE(RISCV_ADDF4,     NULL)
TEMPLATE(RISCV_ADDF8,     NULL)

TEMPLATE(RISCV_SUBI4,    "sub %0, %1, %2")
TEMPLATE(RISCV_SUBU4,    "sub %0, %1, %2")
TEMPLATE(RISCV_SUBF4,    NULL)
TEMPLATE(RISCV_SUBF8,    NULL)

TEMPLATE(RISCV_MULI4,    "mul %0, %1, %2")
TEMPLATE(RISCV_MULU4,    "mul %0, %1, %2")
TEMPLATE(RISCV_MULF4,    NULL)
TEMPLATE(RISCV_MULF8,    NULL)

TEMPLATE(RISCV_DIVI4,    "div %0, %1, %2")
TEMPLATE(RISCV_DIVU4,    "div %0, %1, %2")
TEMPLATE(RISCV_DIVF4,    NULL)
TEMPLATE(RISCV_DIVF8,    NULL)

TEMPLATE(RISCV_MODI4,    "rem %0, %1, %2")
TEMPLATE(RISCV_MODU4,    "rem %0, %1, %2")
TEMPLATE(RISCV_MODF4,    NULL)
TEMPLATE(RISCV_MODF8,    NULL)

TEMPLATE(RISCV_NEGI4,    "neg %0, %1")
TEMPLATE(RISCV_NEGU4,    "neg %0, %1")
TEMPLATE(RISCV_NEGF4,    NULL)
TEMPLATE(RISCV_NEGF8,    NULL)

TEMPLATE(RISCV_COMPI4,   "not %0, %1")
TEMPLATE(RISCV_COMPU4,   "not %0, %1")
TEMPLATE(RISCV_COMPF4,   NULL)
TEMPLATE(RISCV_COMPF8,   NULL)

TEMPLATE(RISCV_JZI4,     "beq %1, 0, %0")
TEMPLATE(RISCV_JZU4,     "beq %1, 0, %0")
TEMPLATE(RISCV_JZF4,     NULL)
TEMPLATE(RISCV_JZF8,     NULL)

TEMPLATE(RISCV_JNZI4,    "bne %1, 0, %0")
TEMPLATE(RISCV_JNZU4,    "bne %1, 0, %0")
TEMPLATE(RISCV_JNZF4,    NULL)
TEMPLATE(RISCV_JNZF8,    NULL)

TEMPLATE(RISCV_JEI4,     "beq %1, %2, %0")
TEMPLATE(RISCV_JEU4,     "beq %1, %2, %0")
TEMPLATE(RISCV_JEF4,     NULL)
TEMPLATE(RISCV_JEF8,     NULL)

TEMPLATE(RISCV_JNEI4,    "bne %1, 0, %0")
TEMPLATE(RISCV_JNEU4,    "bne %1, 0, %0")
TEMPLATE(RISCV_JNEF4,    NULL)
TEMPLATE(RISCV_JNEF8,    NULL)


TEMPLATE(RISCV_JGI4,     "blt %2, %1, %0")
TEMPLATE(RISCV_JGU4,     "blt %2, %1, %0")
TEMPLATE(RISCV_JGF4,     NULL)
TEMPLATE(RISCV_JGF8,     NULL)

TEMPLATE(RISCV_JLI4,     "blt %1, %2, %0")
TEMPLATE(RISCV_JLU4,     "blt %1, %2, %0")
TEMPLATE(RISCV_JLF4,     NULL)
TEMPLATE(RISCV_JLF8,     NULL)

TEMPLATE(RISCV_JGEI4,    "bge %1, %2, %0")
TEMPLATE(RISCV_JGEU4,    "bge %1, %2, %0")
TEMPLATE(RISCV_JGEF4,    NULL)
TEMPLATE(RISCV_JGEF8,    NULL)

TEMPLATE(RISCV_JLEI4,    "bge %2, %1, %0")
TEMPLATE(RISCV_JLEU4,    "bge %2, %1, %0")
TEMPLATE(RISCV_JLEF4,    NULL)
TEMPLATE(RISCV_JLEF8,    NULL)



TEMPLATE(RISCV_EXTI1,    "addi %0, %1, 0")
TEMPLATE(RISCV_EXTU1,    "addi %0, %1, 0")
TEMPLATE(RISCV_EXTI2,    "addi %0, %1, 0")
TEMPLATE(RISCV_EXTU2,    "addi %0, %1, 0")
TEMPLATE(RISCV_TRUI1,    "addi %0, %1, 0")
TEMPLATE(RISCV_TRUI2,    "addi %0, %1, 0")

 
TEMPLATE(RISCV_CVTI4F4,  NULL)
TEMPLATE(RISCV_CVTI4F8,  NULL)
TEMPLATE(RISCV_CVTU4F4,  NULL)
TEMPLATE(RISCV_CVTU4F8,  NULL)

TEMPLATE(RISCV_CVTF4,  NULL) 

 
TEMPLATE(RISCV_CVTF4I4,  NULL)
 
TEMPLATE(RISCV_CVTF4U4,  NULL)
TEMPLATE(RISCV_CVTF8,   NULL)

TEMPLATE(RISCV_CVTF8I4,  NULL)
 
TEMPLATE(RISCV_CVTF8U4,  NULL)
					
		
TEMPLATE(RISCV_INCI1,    "addi %0, %0, 1")
TEMPLATE(RISCV_INCU1,    "addi %0, %0, 1")
TEMPLATE(RISCV_INCI2,    "addi %0, %0, 1")
TEMPLATE(RISCV_INCU2,    "addi %0, %0, 1")				
TEMPLATE(RISCV_INCI4,    "addi %0, %0, 1")
TEMPLATE(RISCV_INCU4,    "addi %0, %0, 1")
TEMPLATE(RISCV_INCF4,    NULL)

 
TEMPLATE(RISCV_INCF8,    NULL)

TEMPLATE(RISCV_DECI1,    "addi %0, %0, -1")
TEMPLATE(RISCV_DECU1,    "addi %0, %0, -1")
TEMPLATE(RISCV_DECI2,    "addi %0, %0, -1")
TEMPLATE(RISCV_DECU2,    "addi %0, %0, -1")
TEMPLATE(RISCV_DECI4,    "addi %0, %0, -1")
TEMPLATE(RISCV_DECU4,    "addi %0, %0, -1")

TEMPLATE(RISCV_DECF4,    NULL)
TEMPLATE(RISCV_DECF8,    NULL)

TEMPLATE(RISCV_LOADIMME2REG,    "li %0, %1")
TEMPLATE(RISCV_JUMP_OFFSET,    "j %0")
TEMPLATE(RISCV_IMMED2MEM,    "li %2, %1;sw %2, %0")
TEMPLATE(RISCV_MEM2REG,    "lw %0, %1")
TEMPLATE(RISCV_REG2MEM,    "sw %1, %0")
TEMPLATE(RISCV_MV_R2R,    "mv %0, %1")
TEMPLATE(RISCV_MEM2REG_OFFSET,    "lw %0, %1(%2)")
TEMPLATE(RISCV_REG2MEM_OFFSET,    "sw %1, %2(%0)")
TEMPLATE(RISCV_REG2STACK,    "sw %0, %1(sp)")

TEMPLATE(RISCV_PROLOGUE, "addi sp, sp, -8;sw  ra, 4(sp);sw s0, 0(sp);mv  s0, sp")
TEMPLATE(RISCV_PUSHM2S,     "addi sp, sp, -4;lw %0, %1;sw %0, 0(sp)")
TEMPLATE(RISCV_PUSHF4,   NULL)
TEMPLATE(RISCV_PUSHF8,   NULL)
TEMPLATE(RISCV_EXPANDF,  "addi sp, sp, -%0")
TEMPLATE(RISCV_LUI_ADDI_LEAL,  "lui %1, %%hi(%2);addi	%0, %1, %%lo(%2)")
TEMPLATE(RISCV_CALL,     "call %1")
TEMPLATE(RISCV_ICALL,    "call *%1")
TEMPLATE(RISCV_REDUCEF,  "addi sp, sp, %0")
TEMPLATE(RISCV_EPILOGUE, "mv sp, s0;lw ra, 4(sp);lw  s0, 0(sp);addi sp, sp, 8;jr	ra")


TEMPLATE(RISCV_LDF4,     NULL)
TEMPLATE(RISCV_LDF8,     NULL)
TEMPLATE(RISCV_STF4,     NULL)
TEMPLATE(RISCV_STF8,     NULL)


TEMPLATE(RISCV_STF4_NO_POP,     NULL)
TEMPLATE(RISCV_STF8_NO_POP,     NULL)

TEMPLATE(RISCV_X87_POP,     NULL)
